# Generated by Django 4.2.2 on 2023-07-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscribedusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribedusers',
            options={'verbose_name_plural': 'SubscribedUsers'},
        ),
    ]
